// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDF7rF0ZWRViZHucCiYr3kPx-vRHFYAmM',
    appId: '1:1082386338976:web:4978010f90489fadae25c5',
    messagingSenderId: '1082386338976',
    projectId: 'muscel-meals',
    authDomain: 'muscel-meals.firebaseapp.com',
    storageBucket: 'muscel-meals.appspot.com',
    measurementId: 'G-W9WK2YGWTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-EZfLzTHQ75KyEtHR7KvoPahl5M5OyE',
    appId: '1:1082386338976:android:020cb65a23892cdaae25c5',
    messagingSenderId: '1082386338976',
    projectId: 'muscel-meals',
    storageBucket: 'muscel-meals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqqlMu-VSgitrozTAzlxPDeTbvD92bY7U',
    appId: '1:1082386338976:ios:1b91b562b68ac9b2ae25c5',
    messagingSenderId: '1082386338976',
    projectId: 'muscel-meals',
    storageBucket: 'muscel-meals.appspot.com',
    iosClientId: '1082386338976-6tnbasdp4b3vr2uu818rfpcp1neeurpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.muscelMeals',
  );
}
